apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-deploy-eks
spec:
  selector:
    matchLabels:
      app: build-deploy-eks
  replicas: 3
  template:
    metadata:
      labels:
        app: build-deploy-eks
    spec:
      containers:
      - name: build-deploy-eks
        image: si3mshady/llm_chat:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: build-deploy-eks-service
spec:
  selector:
    app: build-deploy-eks
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30007